# Generated by Django 4.1.13 on 2023-11-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('t', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
