# Generated by Django 4.1.13 on 2023-11-19 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_test2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
    ]
