# Generated by Django 4.1.13 on 2023-11-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='referential_image_path',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
