# Generated by Django 4.1.13 on 2023-11-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0006_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderdetail',
            table='electronics_orderdetail',
        ),
    ]
