# Generated by Django 4.1.13 on 2023-11-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0007_alter_orderdetail_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='electronics_order',
        ),
    ]
