# Generated by Django 4.1.13 on 2023-11-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0008_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='electronics_customer',
        ),
    ]
