# Generated by Django 4.1.13 on 2023-11-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0009_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='electronics_product',
        ),
    ]
