# Generated by Django 4.1.13 on 2023-11-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0010_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoryproduct',
            table='electronics_categoryproduct',
        ),
    ]
